import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Helper to get __dirname in ESM
const _filename = typeof __filename !== 'undefined'
  ? __filename
  : (typeof import.meta !== 'undefined' && typeof import.meta.url === 'string' ? fileURLToPath(import.meta.url) : '');

const _dirname = typeof __dirname !== 'undefined'
  ? __dirname
  : (_filename ? path.dirname(_filename as string) : '');

export class AiContextGenerator {
  constructor() { }

  async generate(projectRoot: string, n8nVersion: string = "Unknown", extensionPath?: string): Promise<void> {
    const agentsContent = this.getAgentsContent(n8nVersion);

    // 1. AGENTS.md (Central documentation)
    this.injectOrUpdate(path.join(projectRoot, 'AGENTS.md'), agentsContent, true);

    // 2. Local Shim and Gitignore
    this.generateShim(projectRoot, extensionPath);
    this.updateGitignore(projectRoot);
  }

  private generateShim(projectRoot: string, extensionPath?: string): void {
    const shimPath = path.join(projectRoot, 'n8nac-skills');

    // Linux/Mac Shim Logic:
    // 1. If generated by VS Code Extension, we prefer the absolute path to that specific extension version
    // 2. If generated by CLI or if Extension path invalid, we look for local node_modules install

    let extensionCliPathLine = '';
    if (extensionPath) {
      // Updated to use the new bundles path in 'out/skills/cli.js'
      const absolutePath = path.join(extensionPath, 'out', 'skills', 'cli.js');
      const assetsPath = path.join(extensionPath, 'assets');
      extensionCliPathLine = `
# 1. VS Code Extension Context (Explicit absolute path)
if [ -f "${absolutePath}" ]; then
  export N8N_AS_CODE_ASSETS_DIR="${assetsPath}"
  node "${absolutePath}" "$@"
  exit $?
fi`;
    }

    const shimContent = [
      '#!/bin/bash',
      `# n8nac-skills local shim for AI context`,
      extensionCliPathLine,
      ``,
      `# 2. Standard NPM Dependency Context (Local Project)`,
      `# Check for local node_modules relative to the project root`,
      `CLI_PATH="./node_modules/@n8n-as-code/skills/dist/cli.js"`,
      ``,
      `if [ -f "$CLI_PATH" ]; then`,
      `  node "$CLI_PATH" "$@"`,
      `  exit $?`,
      `fi`,
      ``,
      `# 3. Error if not found`,
      `echo "Error: @n8n-as-code/skills not found in ./node_modules/"`,
      `echo "Please ensure it is installed as a dev dependency in this project."`,
      `exit 1`
    ].join('\n');

    fs.writeFileSync(shimPath, shimContent);
    try {
      fs.chmodSync(shimPath, '755'); // Make executable
    } catch (e) {
      console.warn(`Failed to set execution permissions on ${shimPath}:`, e);
    }

    // Windows Shim (simplified to node_modules or extension path if valid)
    const shimPathCmd = path.join(projectRoot, 'n8nac-skills.cmd');
    let cmdContent = '@echo off\n';

    if (extensionPath) {
      const absPath = path.join(extensionPath, 'out', 'skills', 'cli.js');
      const assetsPath = path.join(extensionPath, 'assets');
      cmdContent += `
IF EXIST "${absPath}" (
  SET N8N_AS_CODE_ASSETS_DIR=${assetsPath}
  node "${absPath}" %*
  EXIT /B %ERRORLEVEL%
)
`;
    }

    cmdContent += `
IF EXIST ".\\node_modules\\@n8n-as-code\\skills\\dist\\cli.js" (
  node ".\\node_modules\\@n8n-as-code\\skills\\dist\\cli.js" %*
  EXIT /B %ERRORLEVEL%
)

echo Error: @n8n-as-code/skills not found in node_modules
echo Please ensure it is installed as a dev dependency.
EXIT /B 1
`;

    fs.writeFileSync(shimPathCmd, cmdContent);
  }

  private updateGitignore(projectRoot: string): void {
    const gitignorePath = path.join(projectRoot, '.gitignore');
    const entries = ['\n# n8n-as-code AI helpers', 'n8nac-skills', 'n8nac-skills.cmd'];

    if (!fs.existsSync(gitignorePath)) {
      fs.writeFileSync(gitignorePath, entries.join('\n'));
      return;
    }

    let content = fs.readFileSync(gitignorePath, 'utf8');
    let modified = false;

    for (const entry of entries.filter(e => e.trim().length > 0 && !e.startsWith('#'))) {
      if (!content.includes(entry)) {
        content += (content.endsWith('\n') ? '' : '\n') + entry;
        modified = true;
      }
    }

    if (modified) {
      fs.writeFileSync(gitignorePath, content);
    }
  }

  private injectOrUpdate(filePath: string, content: string, isMarkdownFile: boolean = false): void {
    const startMarker = isMarkdownFile ? '<!-- n8n-as-code-start -->' : '### 🤖 n8n-as-code-start';
    const endMarker = isMarkdownFile ? '<!-- n8n-as-code-end -->' : '### 🤖 n8n-as-code-end';

    const block = `\n${startMarker}\n${content.trim()}\n${endMarker}\n`;

    if (!fs.existsSync(filePath)) {
      // Create new file with header if it's AGENTS.md
      const header = filePath.endsWith('AGENTS.md') ? '# 🤖 AI Agents Guidelines\n' : '';
      fs.writeFileSync(filePath, header + block.trim() + '\n');
      return;
    }

    let existing = fs.readFileSync(filePath, 'utf8');
    const startIdx = existing.indexOf(startMarker);
    const endIdx = existing.indexOf(endMarker);

    if (startIdx !== -1 && endIdx !== -1) {
      // Update existing block while preserving what's before/after
      const before = existing.substring(0, startIdx);
      const after = existing.substring(endIdx + endMarker.length);
      fs.writeFileSync(filePath, before + block.trim() + after);
    } else {
      // Append to end of existing file
      fs.writeFileSync(filePath, existing.trim() + '\n' + block);
    }
  }

  private getAgentsContent(n8nVersion: string): string {
    return [
      `## 🎭 Role: Expert n8n Workflow Engineer`,
      ``,
      `You are a specialized AI agent for creating and editing n8n workflows.`,
      `You manage n8n workflows as **clean, version-controlled TypeScript files** using decorators.`,
      ``,
      `### 🌍 Context`,
      `- **n8n Version**: ${n8nVersion}`,
      `- **Source of Truth**: \`@n8n-as-code/skills\` tools (Deep Search + Technical Schemas)`,
      ``,
      `---`,
      ``,
      `## 🧠 Knowledge Base Priority`,
      ``,
      `1. **PRIMARY SOURCE** (MANDATORY): Use \`@n8n-as-code/skills\` tools for accuracy`,
      `2. **Secondary**: Your trained knowledge (for general concepts only)`,
      `3. **Tertiary**: Code snippets (for quick scaffolding)`,
      ``,
      `---`,
      ``,
      `## 🔬 MANDATORY Research Protocol`,
      ``,
      `**⚠️ CRITICAL**: Before creating or editing ANY node, you MUST follow this protocol:`,
      ``,
      `### Step 0: Pattern Discovery (Intelligence Gathering)`,
      `\`\`\`bash`,
      `./n8nac-skills workflows search "telegram chatbot"`,
      `\`\`\``,
      `- **GOAL**: Don't reinvent the wheel. See how experts build it.`,
      `- **ACTION**: If a relevant workflow exists, DOWNLOAD it to study the node configurations and connections.`,
      `- **LEARNING**: extracting patterns > guessing parameters.`,
      ``,
      `### Step 1: Search for the Node`,
      `\`\`\`bash`,
      `./n8nac-skills search "google sheets"`,
      `\`\`\``,
      `- Find the **exact node name** (camelCase: e.g., \`googleSheets\`)`,
      `- Verify the node exists in current n8n version`,
      ``,
      `### Step 2: Get Exact Schema`,
      `\`\`\`bash`,
      `./n8nac-skills get googleSheets`,
      `\`\`\``,
      `- Get **EXACT parameter names** (e.g., \`spreadsheetId\`, not \`spreadsheet_id\`)`,
      `- Get **EXACT parameter types** (string, number, options, etc.)`,
      `- Get **available operations/resources**`,
      `- Get **required vs optional parameters**`,
      ``,
      `### Step 3: Apply Schema as Absolute Truth`,
      `- **CRITICAL (TYPE)**: The \`type\` field MUST EXACTLY match the \`type\` from schema`,
      `- **CRITICAL (VERSION)**: Use HIGHEST \`typeVersion\` from schema`,
      `- **PARAMETER NAMES**: Use exact names (e.g., \`spreadsheetId\` vs \`spreadsheet_id\`)`,
      `- **NO HALLUCINATIONS**: Do not invent parameter names`,
      ``,
      `### Step 4: Validate Before Finishing`,
      `\`\`\`bash`,
      `./n8nac-skills validate workflow.workflow.ts`,
      `\`\`\``,
      ``,
      `---`,
      ``,
      `## ✅ Node Type & Version Standards`,
      ``,
      `| Rule | Correct | Incorrect |`,
      `| :--- | :--- | :--- |`,
      `| **Full Type** | \`"type": "n8n-nodes-base.switch"\` | \`"type": "switch"\` |`,
      `| **Full Type** | \`"type": "@n8n/n8n-nodes-langchain.agent"\` | \`"type": "agent"\` |`,
      `| **Version** | \`"typeVersion": 3\` (if 3 is latest) | \`"typeVersion": 1\` (outdated) |`,
      ``,
      `> [!IMPORTANT]`,
      `> n8n will display a **"?" (question mark)** if you forget the package prefix. Always use the EXACT \`type\` from \`search\` results!`,
      ``,
      `---`,
      ``,
      `## 🌐 Community Workflows (7000+ Examples)`,
      ``,
      `**Why start from scratch?** Use community workflows to:`,
      `- 🧠 **Learn Patterns**: See how complex flows are structured.`,
      `- ⚡ **Save Time**: Adapt existing logic instead of building from zero.`,
      `- 🔧 **Debug**: Compare your configuration with working examples.`,
      ``,
      `\`\`\`bash`,
      `# 1. Search for inspiration`,
      `./n8nac-skills workflows search "woocommerce sync"`,
      ``,
      `# 2. Download to study or adapt`,
      `./n8nac-skills workflows install 4365 --output reference_workflow.workflow.ts`,
      `\`\`\``,
      ``,
      `---`,
      ``,
      `## �️ Reading Workflow Files Efficiently`,
      ``,
      `Every \`.workflow.ts\` file starts with a \`<workflow-map>\` block — a compact index`,
      `generated automatically at each sync. **Always read this block first** before`,
      `opening the rest of the file.`,
      ``,
      `\`\`\``,
      `// <workflow-map>`,
      `// Workflow : My Workflow`,
      `// Nodes   : 12  |  Connections: 14`,
      `//`,
      `// NODE INDEX`,
      `// ──────────────────────────────────────────────────────────────────`,
      `// Property name                    Node type (short)         Flags`,
      `// ScheduleTrigger                  scheduleTrigger`,
      `// AgentGenerateApplication         agent                      [AI] [creds]`,
      `// GithubCheckBranchRef             httpRequest                [onError→out(1)]`,
      `//`,
      `// ROUTING MAP`,
      `// ──────────────────────────────────────────────────────────────────`,
      `// ScheduleTrigger`,
      `//   → Configuration1`,
      `//     → BuildProfileSources → LoopOverProfileSources`,
      `//       .out(1) → JinaReadProfileSource → LoopOverProfileSources (↩ loop)`,
      `//`,
      `// AI CONNECTIONS`,
      `// AgentIa.uses({ ai_languageModel: OpenaiChatModel, ai_memory: Mmoire })`,
      `// </workflow-map>`,
      `\`\`\``,
      ``,
      `### How to navigate a workflow as an agent`,
      ``,
      `1. **Read \`<workflow-map>\` only** — locate the property name you need`,
      `2. **Search for that property name** in the file (e.g. \`AgentGenerateApplication =\`)`,
      `3. **Read only that section** — do not load the entire file into context`,
      ``,
      `This avoids loading 1500+ lines when you only need to patch 10.`,
      ``,
      `---`,
      ``,      `## 🗺️ Reading Workflow Files Efficiently`,
      ``,
      `Every \`.workflow.ts\` file starts with a \`<workflow-map>\` block — a compact index`,
      `generated automatically at each sync. **Always read this block first** before`,
      `opening the rest of the file.`,
      ``,
      `\`\`\``,
      `// <workflow-map>`,
      `// Workflow : My Workflow`,
      `// Nodes   : 12  |  Connections: 14`,
      `//`,
      `// NODE INDEX`,
      `// ──────────────────────────────────────────────────────────────────`,
      `// Property name                    Node type (short)         Flags`,
      `// ScheduleTrigger                  scheduleTrigger`,
      `// AgentGenerateApplication         agent                      [AI] [creds]`,
      `// GithubCheckBranchRef             httpRequest                [onError→out(1)]`,
      `//`,
      `// ROUTING MAP`,
      `// ──────────────────────────────────────────────────────────────────`,
      `// ScheduleTrigger`,
      `//   → Configuration1`,
      `//     → BuildProfileSources → LoopOverProfileSources`,
      `//       .out(1) → JinaReadProfileSource → LoopOverProfileSources (↩ loop)`,
      `//`,
      `// AI CONNECTIONS`,
      `// AgentIa.uses({ ai_languageModel: OpenaiChatModel, ai_memory: Mmoire })`,
      `// </workflow-map>`,
      `\`\`\``,
      ``,
      `### How to navigate a workflow as an agent`,
      ``,
      `1. **Read \`<workflow-map>\` only** — locate the property name you need`,
      `2. **Search for that property name** in the file (e.g. \`AgentGenerateApplication =\`)`,
      `3. **Read only that section** — do not load the entire file into context`,
      ``,
      `This avoids loading 1500+ lines when you only need to patch 10.`,
      ``,
      `---`,
      ``,      `## �📝 Minimal Workflow Structure`,
      ``,
      `\`\`\`typescript`,
      `import { workflow, node, links } from '@n8n-as-code/core';`,
      ``,
      `@workflow({`,
      `  name: 'Workflow Name',`,
      `  active: false`,
      `})`,
      `export class MyWorkflow {`,
      `  @node({`,
      `    name: 'Descriptive Name',`,
      `    type: '/* EXACT from search */',`,
      `    version: 4,`,
      `    position: [250, 300]`,
      `  })`,
      `  MyNode = {`,
      `    /* parameters from ./n8nac-skills get */`,
      `  };`,
      ``,
      `  @node({`,
      `    name: 'Next Node',`,
      `    type: '/* EXACT from search */',`,
      `    version: 3`,
      `  })`,
      `  NextNode = { /* parameters */ };`,
      ``,
      `  @links()`,
      `  defineRouting() {`,
      `    this.MyNode.out(0).to(this.NextNode.in(0));`,
      `  }`,
      `}`,
      `\`\`\``,
      ``,
      `---`,
      ``,
      `## 🚫 Common Mistakes to AVOID`,
      ``,
      `1. ❌ **Hallucinating parameter names** - Always use \`get\` command first`,
      `2. ❌ **Wrong node type** - Missing package prefix causes "?" icon`,
      `3. ❌ **Outdated typeVersion** - Use highest version from schema`,
      `4. ❌ **Guessing parameter structure** - Check if nested objects required`,
      `5. ❌ **Wrong connection names** - Must match EXACT node \`name\` field`,
      `6. ❌ **Inventing non-existent nodes** - Use \`search\` to verify`,
      ``,
      `---`,
      ``,
      `## ✅ Best Practices`,
      ``,
      `### Node Parameters`,
      `- ✅ Always check schema before writing`,
      `- ✅ Use exact parameter names from schema`,
      `- ❌ Never guess parameter names`,
      ``,
      `### Expressions (Modern Syntax)`,
      `- ✅ Use: \`{{ $json.fieldName }}\` (modern)`,
      `- ✅ Use: \`{{ $('NodeName').item.json.field }}\` (specific nodes)`,
      `- ❌ Avoid: \`{{ $node["Name"].json.field }}\` (legacy)`,
      ``,
      `### Node Naming`,
      `- ✅ "Action Resource" pattern (e.g., "Get Customers", "Send Email")`,
      `- ❌ Avoid generic names like "Node1", "HTTP Request"`,
      ``,
      `### Connections`,
      `- ✅ Regular connections: \`this.NodeA.out(0).to(this.NodeB.in(0))\``,
      `- ✅ AI connections: Use \`.uses()\` for LangChain nodes`,
      `  - Single types: \`ai_languageModel\`, \`ai_memory\`, \`ai_outputParser\`, \`ai_agent\`, \`ai_chain\`, \`ai_textSplitter\`, \`ai_embedding\`, \`ai_retriever\`, \`ai_reranker\`, \`ai_vectorStore\``,
      `  - Array types: \`ai_tool\`, \`ai_document\``,
      `  - Example: \`this.RAG.uses({ ai_embedding: this.Embedding.output, ai_vectorStore: this.VectorStore.output, ai_retriever: this.Retriever.output })\``,
      `- ❌ Never use \`.out().to()\` for AI sub-node connections`,
      ``,
      `---`,
      ``,
      `## 📚 Available Tools`,
      ``,
      `### 🔍 Unified Search (PRIMARY TOOL)`,
      `\`\`\`bash`,
      `./n8nac-skills search "google sheets"`,
      `./n8nac-skills search "how to use RAG"`,
      `\`\`\``,
      `**ALWAYS START HERE.** Deep search across nodes, docs, and tutorials.`,
      ``,
      `### 🛠️ Get Node Schema`,
      `\`\`\`bash`,
      `./n8nac-skills get googleSheets  # Complete info`,
      `./n8nac-skills schema googleSheets  # Quick reference`,
      `\`\`\``,
      ``,
      `### 🌐 Community Workflows`,
      `\`\`\`bash`,
      `./n8nac-skills workflows search "slack notification"`,
      `./n8nac-skills workflows info 916`,
      `./n8nac-skills workflows install 4365`,
      `\`\`\``,
      ``,
      `### 📖 Documentation`,
      `\`\`\`bash`,
      `./n8nac-skills docs "OpenAI"`,
      `./n8nac-skills guides "webhook"`,
      `\`\`\``,
      ``,
      `### ✅ Validate`,
      `\`\`\`bash`,
      `./n8nac-skills validate workflow.workflow.ts`,
      `\`\`\``,
      ``,
      `---`,
      ``,
      `## 🔑 Your Responsibilities`,
      ``,
      `**#1**: Use \`./n8nac-skills\` tools to prevent hallucinations`,
      `**#2**: Follow the exact schema - no assumptions, no guessing`,
      `**#3**: Create workflows that work on the first try`,
      ``,
      `**When in doubt**: \`./n8nac-skills get <nodeName>\``
    ].join('\n');
  }

  private getCursorRulesContent(): string {
    return [
      `# n8n-as-code rules`,
      `- Refer to AGENTS.md for complete n8n workflow standards.`,
      `- MANDATORY: Use 'n8nac-skills' tools before creating/editing nodes.`,
      `- REQUIRED: Use FULL node types (e.g., 'n8n-nodes-base.switch') and LATEST typeVersion.`,
      `- Search: './n8nac-skills search <query>' - Find nodes & docs (PRIMARY TOOL)`,
      `- Get: './n8nac-skills get <nodeName>' - Complete node info`,
      `- Schema: './n8nac-skills schema <nodeName>' - Quick parameters reference`,
      `- Docs: './n8nac-skills docs <title>' - Read a specific documentation page`,
      `- Guides: './n8nac-skills guides <query>' - Find tutorials and examples`,
      `- Workflows: './n8nac-skills workflows search <query>' - Find community workflows (7000+)`,
      `- Related: './n8nac-skills related <nodeName>' - Discover ecosystem and related nodes`,
      `- Validate: './n8nac-skills validate workflow.workflow.ts' - Check your workflow for errors`
    ].join('\n');
  }

  private getClineRulesContent(): string {
    return [
      `n8n_engineer_role:`,
      `  description: Expert in n8n-as-code`,
      `  instructions:`,
      `    - Read AGENTS.md for sync principles.`,
      `    - MANDATORY: Use FULL node types (e.g., 'n8n-nodes-base.switch') and LATEST typeVersion.`,
      `    - Use './n8nac-skills search' as your primary research tool.`,
      `    - Use './n8nac-skills workflows search' to find community examples (7000+ workflows).`,
      `    - Use './n8nac-skills get' to fetch exact schema before editing workflow JSON.`,
      `    - Use './n8nac-skills validate workflow.workflow.ts' to verify your work.`,
      `    - Ensure connections are correctly indexed.`
    ].join('\n');
  }

  private getWindsurfRulesContent(): string {
    return [
      `### n8n Development Rules`,
      `- Follow the Research Protocol in AGENTS.md.`,
      `- Tooling: Use './n8nac-skills' to fetch node schemas and documentation.`,
    ].join('\n');
  }

  private getCommonRulesContent(): string {
    return [
      `# Common Rules for All AI Agents (Claude, Mistral, etc.)`,
      `- Role: Expert n8n Automation Engineer.`,
      `- Workflow Source of Truth: './n8nac-skills' tools.`,
      `- Documentation: Read AGENTS.md for full syntax rules.`
    ].join('\n');
  }
}
